/**
 * Cross-language conformance: the TypeScript implementation must reproduce, exactly,
 * what the Python implementation produced for the same inputs.
 *
 * Fixtures are generated by `python scripts/make_golden.py`. If this test fails, one of
 * the two implementations has drifted from shared/spec/features.md. Decide which one is
 * wrong by reading the spec — do not "fix" the fixture to make the test pass.
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { extractFeatures } from './features';

const GOLDEN = resolve(dirname(fileURLToPath(import.meta.url)), '../../shared/golden');

function readJsonl<T>(name: string): T[] {
  return readFileSync(resolve(GOLDEN, name), 'utf8')
    .split('\n')
    .filter((l) => l !== '')
    .map((l) => JSON.parse(l) as T);
}

interface GoldenToken {
  c: number;
  s: number;
  e: number;
  r: number[];
  p: [number, number];
}

const inputs = readJsonl<string>('inputs.jsonl');
const expected = readJsonl<{ t: GoldenToken[] }>('features.jsonl');

describe('golden fixtures', () => {
  it('has matching input and expectation counts', () => {
    expect(inputs).toHaveLength(expected.length);
    expect(inputs.length).toBeGreaterThan(1500);
  });

  it('matches the Python implementation on every input', () => {
    const failures: string[] = [];

    for (let i = 0; i < inputs.length; i++) {
      const text = inputs[i]!;
      const want = expected[i]!.t;
      const got = extractFeatures(text).map((f) => ({
        c: f.cls,
        s: f.start,
        e: f.end,
        r: f.rows,
        p: [f.sentenceFirstWord, f.prevSentenceLastWord] as [number, number],
      }));

      if (JSON.stringify(got) !== JSON.stringify(want)) {
        failures.push(
          `input[${i}] ${JSON.stringify(text)}\n  want ${JSON.stringify(want)}\n  got  ${JSON.stringify(got)}`,
        );
        if (failures.length >= 5) break;
      }
    }

    expect(failures.join('\n\n')).toBe('');
  });

  it('round-trips every input through its token spans', () => {
    for (const text of inputs) {
      const normalized = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
      const joined = extractFeatures(text)
        .map((f) => f.text)
        .join('');
      expect(joined).toBe(normalized);
    }
  });
});
