/**
 * Cross-language conformance for the learned Blelloch scan.
 *
 * The scan's combine operator carries a different parameter at each tree level, so it is
 * not associative — it describes one specific balanced binary tree. Any reimplementation
 * that walks a different tree produces plausible-looking but wrong numbers, and nothing
 * else in the test suite would catch it. Hence this fixture.
 *
 * Generated by `python3 scripts/make_scan_golden.py`.
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { blelloch } from './cpu';
import { D } from './model';

const GOLDEN = resolve(dirname(fileURLToPath(import.meta.url)), '../../shared/golden/scan.jsonl');

interface ScanCase {
  n: number;
  npad: number;
  z: number[];
  w: number[];
  up: number[];
  down: number[];
  out: number[];
}

const cases: ScanCase[] = readFileSync(GOLDEN, 'utf8')
  .split('\n')
  .filter((l) => l !== '')
  .map((l) => JSON.parse(l) as ScanCase);

describe('scan conformance with PyTorch', () => {
  it('covers several lengths including powers of two and their neighbours', () => {
    expect(cases.length).toBeGreaterThanOrEqual(8);
    expect(cases.map((c) => c.n)).toContain(1);
    expect(cases.map((c) => c.n)).toContain(9);
  });

  for (const c of cases) {
    it(`matches at n=${c.n} (padded to ${c.npad})`, () => {
      const got = blelloch(
        Float32Array.from(c.z),
        Float32Array.from(c.w),
        c.n,
        Float32Array.from(c.up),
        Float32Array.from(c.down),
      );

      expect(got).toHaveLength(c.n * D);
      let worst = 0;
      for (let i = 0; i < c.n * D; i++) {
        worst = Math.max(worst, Math.abs(got[i]! - c.out[i]!));
      }
      // float32 in TypeScript against float64 in PyTorch, so exact equality is not on
      // offer; anything above this is a structural difference, not rounding.
      expect(worst).toBeLessThan(1e-5);
    });
  }
});
